export const TRY_FETCH_REPOSITORIES = 'TRY_FETCH_REPOSITORIES';
export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES';
export const TRY_FETCH_REPOSITORY = 'TRY_FETCH_REPOSITORY';
export const FETCH_REPOSITORY = 'FETCH_REPOSITORY';
