export const TRY_FETCH_CONTRIBUTORS = 'TRY_FETCH_CONTRIBUTORS';
export const FETCH_CONTRIBUTORS = 'FETCH_CONTRIBUTORS';
export const TRY_SET_CONTRIBUTORS = 'TRY_SET_CONTRIBUTORS';
export const SET_CONTRIBUTORS = 'SET_CONTRIBUTORS';
export const TRY_UPDATE_CONTRIBUTORS = 'TRY_UPDATE_CONTRIBUTORS';
export const UPDATE_CONTRIBUTORS = 'UPDATE_CONTRIBUTORS';
